apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmchart-sample.fullname" . }}
  labels:
    {{- include "helmchart-sample.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - port: {{ $value.port }}
      targetPort: {{ $value.port }}
      protocol: {{ $value.protocol }}
      name: {{ $key }}
    {{- end }}
  selector:
    {{- include "helmchart-sample.selectorLabels" . | nindent 4 }}
